"use client";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowRight, BookOpen, Check, ChevronDown, Heart, MessageCircle, PenLine, Quote, Sparkles, Star } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";

const whatsapp = "https://wa.me/94770000000?text=" + encodeURIComponent("வணக்கம்! என் கதையை ஒரு புத்தகமாக மாற்ற விரும்புகிறேன்.");
const services = [
  ["காதல் கதை", "Love Story", "காதலின் முதல் சந்திப்பிலிருந்து வாழ்நாள் பயணம் வரை.", "❤️"],
  ["குடும்ப நினைவுகள்", "Family Story", "உங்கள் குடும்பத்தின் அழகிய பாரம்பரியத்தைப் பாதுகாப்போம்.", "👨‍👩‍👧"],
  ["வீட்டின் பயணம்", "House Journey", "கனவிலிருந்து இல்லம் வரை ஒவ்வொரு அத்தியாயமும்.", "🏠"],
  ["பெற்றோர் வரலாறு", "Parents Memoir", "அன்பும் தியாகமும் நிறைந்த அவர்களின் வாழ்க்கை.", "👵"],
  ["திருமண நினைவுகள்", "Wedding Story", "உங்கள் சிறப்பான நாளை என்றும் வாழும் கதையாக்குவோம்.", "💍"],
  ["தொழில் பயணம்", "Business Journey", "ஒரு கனவின் தொடக்கமும் அதன் வெற்றியும்.", "💼"],
];
const covers = [
  ["எங்கள் காதல்", "Love Story", "#7a293b", "A & S"], ["எங்கள் வேர்கள்", "Family Heritage", "#304b3c", "1958"], ["எங்கள் வீடு", "A House Journey", "#3e566b", "HOME"], ["அப்பாவின் கதை", "A Father's Memoir", "#764c32", "1963"], ["எங்கள் நாள்", "Wedding Memories", "#8a5660", "K & M"]
];
const serviceDescriptions = ["From your first meeting to a lifetime journey of love.", "Preserve your family’s beautiful heritage for generations.", "Every chapter from a dream to the home you built.", "A life of love and sacrifice, held close forever.", "Let your special day live on as a beautiful story.", "The beginning of a dream and the path to success."];
const testimonials = [
  ["என் அப்பாவின் வாழ்க்கை கதையை புத்தகமாக கொடுத்தபோது அவர் கண்களில் கண்ணீர் வந்தது.", "When we gave my father his life story as a book, there were tears in his eyes."],
  ["எங்கள் காதல் பயணத்தை புத்தகமாக மாற்றிய விதம் மிகவும் அழகாக இருந்தது.", "The way they turned our journey of love into a book was truly beautiful."],
  ["வீடு கட்டிய பயணத்தை புத்தகமாக வைத்திருப்பது எங்கள் குடும்பத்திற்கு ஒரு பொக்கிஷம்.", "Keeping our home-building journey as a book is a treasure for our family."]
];
const faqs = [["எப்படி என் கதையைப் பகிர்வது?", "WhatsApp அழைப்பு அல்லது நேர்காணல் மூலம் எங்கள் எழுத்தாளர் உங்கள் நினைவுகளை அன்புடன் கேட்பார்."], ["புத்தகம் தயாராக எவ்வளவு நாட்கள் ஆகும்?", "உங்கள் கதையின் நீளத்தைப் பொறுத்து பொதுவாக 2 முதல் 4 வாரங்கள் ஆகும்."], ["புகைப்படங்களைச் சேர்க்க முடியுமா?", "ஆம். உங்கள் புகைப்படங்களை ஒரு கலைநயமான நினைவுப் புத்தகமாக வடிவமைப்போம்."]];

function SectionTitle({eyebrow, title, text}:{eyebrow:string,title:string,text?:string}) { return <div className="max-w-2xl"><p className="mb-3 text-xs font-bold uppercase tracking-[.22em] text-gold">{eyebrow}</p><h2 className="font-serif text-3xl leading-tight text-wine md:text-5xl">{title}</h2>{text && <p className="mt-4 leading-7 text-stone-600">{text}</p>}</div> }
function Button({children, secondary=false, href=whatsapp}:{children:React.ReactNode,secondary?:boolean,href?:string}) { return <a href={href} target="_blank" className={"inline-flex items-center gap-2 rounded-full px-5 py-3 text-sm font-bold transition hover:-translate-y-0.5 " + (secondary ? "border border-wine bg-white text-wine" : "bg-wine text-white shadow-lg shadow-wine/20")}>{children}<ArrowRight size={16}/></a> }

export default function Home() {
 const [en,setEn]=useState(false); const [activeTestimonial,setActiveTestimonial]=useState(0);
 const t=(ta:string,enText:string)=>en?enText:ta;
 useEffect(()=>{ document.title = en ? "Memory Stories | Personalized Story Books" : "நினைவு கதைகள் | தனிப்பயன் கதை புத்தகங்கள்"; },[en]);
 useEffect(()=>{ const timer=window.setInterval(()=>setActiveTestimonial(current=>(current+1)%testimonials.length),5000); return ()=>window.clearInterval(timer); },[]);
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault(); const f=new FormData(e.currentTarget); const msg=`Hello! I would like a story book.%0AName: ${f.get("name")}%0APhone: ${f.get("phone")}%0AStory: ${f.get("story")}%0AMessage: ${f.get("message")}`; window.open(`https://wa.me/94770000000?text=${msg}`,"_blank")};
 return <main className="overflow-hidden">
  <nav className="fixed inset-x-0 top-0 z-40 border-b border-wine/10 bg-cream/90 backdrop-blur"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5"><a href="#home" className="font-serif text-xl font-bold text-wine">{en ? <>Memory <span className="text-gold">Stories</span></> : <>நினைவு <span className="text-gold">கதைகள்</span></>}</a><div className="hidden items-center gap-6 text-sm font-medium md:flex"><a href="#services">{t("சேவைகள்","Services")}</a><a href="#portfolio">{t("புத்தகங்கள்","Books")}</a><a href="#pricing">{t("விலை","Pricing")}</a><a href="#about">{t("எங்களைப் பற்றி","About us")}</a><a href="#contact">{t("தொடர்பு","Contact")}</a></div><button onClick={()=>setEn(!en)} className="rounded-full border border-gold/60 px-3 py-1.5 text-xs font-bold text-wine">{en?"தமிழ்":"EN"}</button></div></nav>
  <section id="home" className="relative min-h-[760px] bg-wine pt-20 text-white"><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(58,12,20,.94)_0%,rgba(100,31,43,.82)_43%,rgba(100,31,43,.25)_100%)]"/><div className="absolute right-0 top-0 hidden h-full w-[55%] bg-[url('/images/hero-family.png')] bg-cover bg-center md:block"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_16%_18%,rgba(200,155,75,.22),transparent_25%)]"/><div className="relative mx-auto flex min-h-[680px] max-w-7xl items-center px-5"><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.75}} className="max-w-2xl"><p className="mb-5 flex items-center gap-2 text-sm tracking-[.18em] text-[#e9c777]"><Sparkles size={16}/>{t("உங்கள் நினைவுகள், எங்கள் கலை","YOUR MEMORIES, OUR CRAFT")}</p><h1 className="font-serif text-5xl leading-[1.12] md:text-7xl">{t("உங்கள் வாழ்க்கை ஒரு அழகான புத்தகமாக", "Turn Your Life Story Into A Beautiful Book")}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-white/78">{t("நினைவுகளை தலைமுறைகள் கடந்து பாதுகாப்போம். உங்கள் கதை, உங்கள் குரலில், என்றும் வாழும் ஒரு புத்தகமாக.","Preserve the moments that made you — thoughtfully written, beautifully designed, forever yours.")}</p><div className="mt-8 flex flex-wrap gap-3"><Button>{t("உங்கள் கதையைத் தொடங்குங்கள்","Begin Your Story")}</Button><Button secondary href="#how">{t("எப்படி வேலை செய்கிறது","How it works")}</Button></div><div className="mt-12 flex gap-8 text-sm"><span><b className="block text-2xl text-[#e9c777]">500+</b>{t("நினைவுகள் பாதுகாக்கப்பட்டன","Stories preserved")}</span><span><b className="block text-2xl text-[#e9c777]">4.9/5</b>{t("குடும்ப அன்பு","Families love us")}</span></div></motion.div></div></section>
  <section id="how" className="texture py-24"><div className="mx-auto max-w-7xl px-5"><SectionTitle eyebrow="OUR PROCESS" title={t("உங்கள் கதை பிறக்கும் நான்கு அழகிய படிகள்", "Four thoughtful steps to your book")}/><div className="mt-12 grid gap-5 md:grid-cols-4">{[["01","பகிருங்கள்","Share Your Story",MessageCircle],["02","எழுதுகிறோம்","We Write",PenLine],["03","வடிவமைக்கிறோம்","We Design",Sparkles],["04","உங்களிடம்","We Deliver",BookOpen]].map(([num,taName,enName,Icon]:any)=><motion.div whileHover={{y:-6}} key={num} className="border border-wine/10 bg-white p-7"><span className="text-sm text-gold">{num}</span><Icon className="my-6 text-wine"/><h3 className="font-serif text-xl text-wine">{en?enName:taName}</h3><p className="mt-2 text-sm leading-6 text-stone-600">{t("அன்புடன், உங்கள் வசதிக்கு ஏற்றபடி.","At your pace, with our gentle guidance.")}</p></motion.div>)}</div></div></section>
  <section id="services" className="py-24"><div className="mx-auto max-w-7xl px-5"><SectionTitle eyebrow="STORIES WE HOLD" title={t("ஒவ்வொரு வாழ்க்கைக்கும் ஒரு புத்தகம்", "A book for every life")} text={t("காதல், குடும்பம், கனவுகள் — எந்த நினைவும் சிறியது அல்ல.","Love, family, milestones — no memory is too small to become a legacy.")}/><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.map(([ta,enName,desc,emoji],index)=><motion.article whileHover={{y:-6}} key={ta} className="group relative overflow-hidden rounded-sm bg-[#f4eadb] p-7"><div className="absolute right-4 top-3 text-5xl opacity-20 transition group-hover:scale-125">{emoji}</div><h3 className="relative font-serif text-2xl text-wine">{en?enName:ta}</h3><p className="relative mt-3 max-w-[16rem] text-sm leading-6 text-stone-600">{en?serviceDescriptions[index]:desc}</p><a href={whatsapp} className="relative mt-7 inline-flex items-center gap-2 text-sm font-bold text-wine">{t("விசாரிக்கவும்","Enquire")} <ArrowRight size={15}/></a></motion.article>)}</div></div></section>
  <section id="portfolio" className="bg-wine py-24 text-white"><div className="mx-auto max-w-7xl px-5"><SectionTitle eyebrow="A GLIMPSE INSIDE" title={t("கைகளில் பிடிக்கக்கூடிய நினைவுகள்", "Memories made tangible")} text={t("ஒவ்வொரு புத்தகமும் உங்கள் நினைவுகளைத் தொடும் வகையில் கலைநயமாக உருவாக்கப்படுகிறது.", "Each book is artfully crafted to make your memories feel close again.")}/><motion.div initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.65}} className="mt-12 overflow-hidden rounded-sm border border-gold/30 bg-[#3e151d] p-3 shadow-2xl"><img src="/images/memory-books.png" alt="A collection of premium handcrafted memory books" className="h-auto w-full object-cover transition duration-700 hover:scale-[1.02]"/></motion.div><div className="mt-7 flex flex-wrap justify-center gap-x-8 gap-y-3 text-sm text-white/70">{[t("காதல் கதை", "Love stories"),t("குடும்ப பாரம்பரியம்", "Family heritage"),t("திருமண நினைவுகள்", "Wedding memories"),t("வாழ்க்கைப் பயணம்", "Life journeys")].map(label=><span key={label} className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-gold"/>{label}</span>)}</div></div></section>  <section id="pricing" className="py-24"><div className="mx-auto max-w-7xl px-5 text-center"><div className="mx-auto max-w-xl"><SectionTitle eyebrow="CHOOSE YOUR LEGACY" title={t("உங்கள் கதைக்கான சிறந்த வடிவம்", "The right form for your story")}/></div><div className="mt-12 grid gap-6 md:grid-cols-3">{[["Starter","தொடக்கம்",["Story writing","PDF delivery"]],["Premium","அழகு",["Story writing","Premium design","PDF delivery"]],["Luxury","பாரம்பரியம்",["Story writing","Premium design","Print support","Gift-ready finish"]]].map(([name,ta,items],i)=><div key={String(name)} className={`relative border p-8 text-left ${i===1?"border-gold bg-wine text-white shadow-xl":"border-wine/10 bg-white"}`}>{i===1&&<span className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-gold px-4 py-1 text-xs font-bold text-wine">MOST LOVED</span>}<p className="text-xs uppercase tracking-[.18em] text-gold">{name}</p><h3 className={`mt-3 font-serif text-3xl ${i===1?"":"text-wine"}`}>{en ? name : ta}</h3><div className="my-7 h-px bg-current opacity-15"/><ul className="space-y-3 text-sm">{(items as string[]).map(x=><li key={x} className="flex gap-2"><Check size={17} className="text-gold"/>{x}</li>)}</ul><a href={whatsapp} className={`mt-8 inline-block text-sm font-bold ${i===1?"text-[#e9c777]":"text-wine"}`}>{t("விலை கேளுங்கள் →","Ask for pricing →")}</a></div>)}</div><p className="mt-6 text-sm text-stone-500">{t("உங்கள் கனவுக்கு ஏற்ப தனிப்பயன் விலையும் உண்டு.","Custom pricing is available for your one-of-a-kind story.")}</p></div></section>
  <section id="about" className="bg-[#f0e4d2] py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 md:grid-cols-2 md:items-center"><div><SectionTitle eyebrow="WHY WE EXIST" title={t("நினைவுகள் மறக்கப்படக் கூடாது", "Memories deserve to outlive the moment")} text={t("ஒரு வீட்டில் சொல்லப்படும் கதைகள், நாளை ஒரு குடும்பத்தின் வேர்களாக மாறுகின்றன. அவற்றை அன்புடன் எழுதிப் பாதுகாப்பதே எங்கள் பணி.","The stories told in a home become a family’s roots. We give them a lasting, beautiful place to live.")}/><div className="mt-7 flex items-center gap-4"><div className="grid h-12 w-12 place-items-center rounded-full bg-wine text-gold">A</div><div><b className="text-wine">Ananya Raman</b><p className="text-sm text-stone-600">Founder & Story Keeper</p></div></div></div><blockquote className="border-l-2 border-gold pl-8 font-serif text-3xl leading-relaxed text-wine">“{t("ஒவ்வொரு குடும்பத்திலும் எழுதப்படக் காத்திருக்கும் ஒரு நூல் இருக்கிறது.","Every family has a book waiting to be written.")}”</blockquote></div></section>
  <section className="py-24"><div className="mx-auto max-w-4xl px-5"><SectionTitle eyebrow={t("எங்கள் குடும்பங்களிடமிருந்து", "FROM OUR FAMILIES")} title={t("அன்பால் எழுதப்பட்ட வார்த்தைகள்", "Words from the families we serve")}/><div className="mt-10 overflow-hidden"><AnimatePresence mode="wait"><motion.article key={activeTestimonial} initial={{opacity:0,x:36}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-36}} transition={{duration:.45}} className="border border-wine/10 bg-white p-8 md:p-12"><Quote className="text-gold" size={34}/><p className="mt-6 font-serif text-2xl leading-relaxed text-wine md:text-3xl">“{en?testimonials[activeTestimonial][1]:testimonials[activeTestimonial][0]}”</p><div className="mt-8 flex items-center justify-between"><div className="flex items-center gap-1 text-gold">{[1,2,3,4,5].map(x=><Star key={x} size={14} fill="currentColor"/>)}</div><span className="text-sm text-stone-500">{en?["Meena & family","Arun & Kavya","Rajesh family"][activeTestimonial]:["மீனா & குடும்பம்","அருண் & காவ்யா","ராஜேஷ் குடும்பம்"][activeTestimonial]}</span></div></motion.article></AnimatePresence><div className="mt-5 flex justify-center gap-2">{testimonials.map((_,i)=><button key={i} onClick={()=>setActiveTestimonial(i)} aria-label={`Show testimonial ${i+1}`} className={`h-2 rounded-full transition-all ${i===activeTestimonial?"w-7 bg-gold":"w-2 bg-wine/20"}`}/>)}</div></div></div></section>
  <section id="contact" className="py-24"><div className="mx-auto grid max-w-5xl gap-12 px-5 md:grid-cols-2"><SectionTitle eyebrow="BEGIN YOUR BOOK" title={t("உங்கள் கதையை எங்களுக்குச் சொல்லுங்கள்", "Tell us about your story")}/><form onSubmit={submit} className="grid gap-4"><input required name="name" placeholder={t("உங்கள் பெயர்","Your name")} className="border border-wine/20 bg-white p-3 outline-none focus:border-gold"/><input required name="phone" placeholder={t("தொலைபேசி எண்","Phone number")} className="border border-wine/20 bg-white p-3 outline-none focus:border-gold"/><select name="story" className="border border-wine/20 bg-white p-3"><option>{t("கதை வகையைத் தேர்ந்தெடுங்கள்","Select story type")}</option>{services.map(x=><option key={x[0]}>{x[0]}</option>)}</select><textarea name="message" placeholder={t("உங்கள் கதையைப் பற்றி சில வார்த்தைகள்...","A few words about your story...")} rows={4} className="border border-wine/20 bg-white p-3 outline-none focus:border-gold"/><button className="flex items-center justify-center gap-2 bg-wine p-3 font-bold text-white">{t("WhatsApp-ல் அனுப்புங்கள்","Send on WhatsApp")}<MessageCircle size={17}/></button></form></div></section>
  <footer className="border-t border-wine/10 px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 text-sm text-stone-500 md:flex-row"><p className="font-serif text-wine">நினைவு <span className="text-gold">கதைகள்</span></p><p>© 2026 Ninaivu Kadhaigal. {t("நினைவுகளை பாதுகாப்போம்.","Made for stories that matter.")}</p></div></footer>
  <a href={whatsapp} target="_blank" className="fixed bottom-5 right-5 z-50 flex items-center gap-2 rounded-full bg-[#25D366] px-5 py-3 text-sm font-bold text-white shadow-xl transition hover:-translate-y-0.5"><MessageCircle size={18}/>{t("WhatsApp-ல் பேசுங்கள்","Chat on WhatsApp")}</a>
 </main>
}

